const mongoose = require("mongoose");



const dataSchema=new mongoose.Schema({
  data:{type:Number, unique: true },
  attent:{ type: String}
})

const attendanceSchema = new mongoose.Schema(
  {
    staffId: {
      type: String,
      required: true,
 // Assuming there's a Staff model
    },
    staffName: {
      type: String,
      required: true,
 // Assuming there's a Staff model
    },
    year: {
      type: String,
      default:new Date().getFullYear()
    },
    joinigdate:{
      type: String,
      default:String(new Date())

    },
    January:{
      type:[Object],
      default:[{data: 1,
        attent:""},{data: 2,
          attent:""},{data: 3,
            attent:""},{data:4,
              attent:""},{data: 5,
                attent:""},{data: 6,
                  attent:""},{data: 7,
                    attent:""},{data: 8,
                      attent:""},{data: 9,
                        attent:""},{data: 10,
                          attent:""},{data: 11,
                            attent:""},{data: 12,
                              attent:""},{data: 13,
                                attent:""},{data: 14,
                                  attent:""},{data: 15,
                                    attent:""},{data: 16,
                                      attent:""},{data: 17,
                                        attent:""},{data: 18,
                                          attent:""},{data: 19,
                                            attent:""},{data: 20,
                                              attent:""},{data: 21,
                                                attent:""},{data:22,
                                                  attent:""},{data:23,
                                                    attent:""},{data: 24,
                                                      attent:""},{data: 25,
                                                        attent:""},{data: 26,
                                                          attent:""},{data: 27,
                                                            attent:""},{data: 28,
                                                            attent:""},{data: 29,
                                                              attent:""},{data: 30,
                                                                attent:""},{data: 31,
                                                                  attent:""}]
    },
    February:{
      type:[Object],
      default:[{data: 1,
        attent:""},{data: 2,
          attent:""},{data: 3,
            attent:""},{data:4,
              attent:""},{data: 5,
                attent:""},{data: 6,
                  attent:""},{data: 7,
                    attent:""},{data: 8,
                      attent:""},{data: 9,
                        attent:""},{data: 10,
                          attent:""},{data: 11,
                            attent:""},{data: 12,
                              attent:""},{data: 13,
                                attent:""},{data: 14,
                                  attent:""},{data: 15,
                                    attent:""},{data: 16,
                                      attent:""},{data: 17,
                                        attent:""},{data: 18,
                                          attent:""},{data: 19,
                                            attent:""},{data: 20,
                                              attent:""},{data: 21,
                                                attent:""},{data:22,
                                                  attent:""},{data:23,
                                                    attent:""},{data: 24,
                                                      attent:""},{data: 25,
                                                        attent:""},{data: 26,
                                                          attent:""},{data: 27,
                                                            attent:""},{data: 28,
                                                            attent:""},{data: 29,
                                                              attent:""},{data: 30,
                                                                attent:""},{data: 31,
                                                                  attent:""}]
    },
    
    March:{
      type:[Object],
      default:[{data: 1,
        attent:""},{data: 2,
          attent:""},{data: 3,
            attent:""},{data:4,
              attent:""},{data: 5,
                attent:""},{data: 6,
                  attent:""},{data: 7,
                    attent:""},{data: 8,
                      attent:""},{data: 9,
                        attent:""},{data: 10,
                          attent:""},{data: 11,
                            attent:""},{data: 12,
                              attent:""},{data: 13,
                                attent:""},{data: 14,
                                  attent:""},{data: 15,
                                    attent:""},{data: 16,
                                      attent:""},{data: 17,
                                        attent:""},{data: 18,
                                          attent:""},{data: 19,
                                            attent:""},{data: 20,
                                              attent:""},{data: 21,
                                                attent:""},{data:22,
                                                  attent:""},{data:23,
                                                    attent:""},{data: 24,
                                                      attent:""},{data: 25,
                                                        attent:""},{data: 26,
                                                          attent:""},{data: 27,
                                                            attent:""},{data: 28,
                                                            attent:""},{data: 29,
                                                              attent:""},{data: 30,
                                                                attent:""},{data: 31,
                                                                  attent:""}]
    },
    April:{
      type:[Object],
      default:[{data: 1,
        attent:""},{data: 2,
          attent:""},{data: 3,
            attent:""},{data:4,
              attent:""},{data: 5,
                attent:""},{data: 6,
                  attent:""},{data: 7,
                    attent:""},{data: 8,
                      attent:""},{data: 9,
                        attent:""},{data: 10,
                          attent:""},{data: 11,
                            attent:""},{data: 12,
                              attent:""},{data: 13,
                                attent:""},{data: 14,
                                  attent:""},{data: 15,
                                    attent:""},{data: 16,
                                      attent:""},{data: 17,
                                        attent:""},{data: 18,
                                          attent:""},{data: 19,
                                            attent:""},{data: 20,
                                              attent:""},{data: 21,
                                                attent:""},{data:22,
                                                  attent:""},{data:23,
                                                    attent:""},{data: 24,
                                                      attent:""},{data: 25,
                                                        attent:""},{data: 26,
                                                          attent:""},{data: 27,
                                                            attent:""},{data: 28,
                                                            attent:""},{data: 29,
                                                              attent:""},{data: 30,
                                                                attent:""},{data: 31,
                                                                  attent:""}]
    },
    May:{
      type:[Object],
      default:[{data: 1,
        attent:""},{data: 2,
          attent:""},{data: 3,
            attent:""},{data:4,
              attent:""},{data: 5,
                attent:""},{data: 6,
                  attent:""},{data: 7,
                    attent:""},{data: 8,
                      attent:""},{data: 9,
                        attent:""},{data: 10,
                          attent:""},{data: 11,
                            attent:""},{data: 12,
                              attent:""},{data: 13,
                                attent:""},{data: 14,
                                  attent:""},{data: 15,
                                    attent:""},{data: 16,
                                      attent:""},{data: 17,
                                        attent:""},{data: 18,
                                          attent:""},{data: 19,
                                            attent:""},{data: 20,
                                              attent:""},{data: 21,
                                                attent:""},{data:22,
                                                  attent:""},{data:23,
                                                    attent:""},{data: 24,
                                                      attent:""},{data: 25,
                                                        attent:""},{data: 26,
                                                          attent:""},{data: 27,
                                                            attent:""},{data: 28,
                                                            attent:""},{data: 29,
                                                              attent:""},{data: 30,
                                                                attent:""},{data: 31,
                                                                  attent:""}]
    },
    June:{
      type:[Object],
      default:[{data: 1,
        attent:""},{data: 2,
          attent:""},{data: 3,
            attent:""},{data:4,
              attent:""},{data: 5,
                attent:""},{data: 6,
                  attent:""},{data: 7,
                    attent:""},{data: 8,
                      attent:""},{data: 9,
                        attent:""},{data: 10,
                          attent:""},{data: 11,
                            attent:""},{data: 12,
                              attent:""},{data: 13,
                                attent:""},{data: 14,
                                  attent:""},{data: 15,
                                    attent:""},{data: 16,
                                      attent:""},{data: 17,
                                        attent:""},{data: 18,
                                          attent:""},{data: 19,
                                            attent:""},{data: 20,
                                              attent:""},{data: 21,
                                                attent:""},{data:22,
                                                  attent:""},{data:23,
                                                    attent:""},{data: 24,
                                                      attent:""},{data: 25,
                                                        attent:""},{data: 26,
                                                          attent:""},{data: 27,
                                                            attent:""},{data: 28,
                                                            attent:""},{data: 29,
                                                              attent:""},{data: 30,
                                                                attent:""},{data: 31,
                                                                  attent:""}]
    },
    July:{
      type:[Object],
      default:[{data: 1,
        attent:""},{data: 2,
          attent:""},{data: 3,
            attent:""},{data:4,
              attent:""},{data: 5,
                attent:""},{data: 6,
                  attent:""},{data: 7,
                    attent:""},{data: 8,
                      attent:""},{data: 9,
                        attent:""},{data: 10,
                          attent:""},{data: 11,
                            attent:""},{data: 12,
                              attent:""},{data: 13,
                                attent:""},{data: 14,
                                  attent:""},{data: 15,
                                    attent:""},{data: 16,
                                      attent:""},{data: 17,
                                        attent:""},{data: 18,
                                          attent:""},{data: 19,
                                            attent:""},{data: 20,
                                              attent:""},{data: 21,
                                                attent:""},{data:22,
                                                  attent:""},{data:23,
                                                    attent:""},{data: 24,
                                                      attent:""},{data: 25,
                                                        attent:""},{data: 26,
                                                          attent:""},{data: 27,
                                                            attent:""},{data: 28,
                                                            attent:""},{data: 29,
                                                              attent:""},{data: 30,
                                                                attent:""},{data: 31,
                                                                  attent:""}]
    },
    August:{
      type:[Object],
      default:[{data: 1,
        attent:""},{data: 2,
          attent:""},{data: 3,
            attent:""},{data:4,
              attent:""},{data: 5,
                attent:""},{data: 6,
                  attent:""},{data: 7,
                    attent:""},{data: 8,
                      attent:""},{data: 9,
                        attent:""},{data: 10,
                          attent:""},{data: 11,
                            attent:""},{data: 12,
                              attent:""},{data: 13,
                                attent:""},{data: 14,
                                  attent:""},{data: 15,
                                    attent:""},{data: 16,
                                      attent:""},{data: 17,
                                        attent:""},{data: 18,
                                          attent:""},{data: 19,
                                            attent:""},{data: 20,
                                              attent:""},{data: 21,
                                                attent:""},{data:22,
                                                  attent:""},{data:23,
                                                    attent:""},{data: 24,
                                                      attent:""},{data: 25,
                                                        attent:""},{data: 26,
                                                          attent:""},{data: 27,
                                                            attent:""},{data: 28,
                                                            attent:""},{data: 29,
                                                              attent:""},{data: 30,
                                                                attent:""},{data: 31,
                                                                  attent:""}]
    },
    September:{
      type:[Object],
      default:[{data: 1,
        attent:""},{data: 2,
          attent:""},{data: 3,
            attent:""},{data:4,
              attent:""},{data: 5,
                attent:""},{data: 6,
                  attent:""},{data: 7,
                    attent:""},{data: 8,
                      attent:""},{data: 9,
                        attent:""},{data: 10,
                          attent:""},{data: 11,
                            attent:""},{data: 12,
                              attent:""},{data: 13,
                                attent:""},{data: 14,
                                  attent:""},{data: 15,
                                    attent:""},{data: 16,
                                      attent:""},{data: 17,
                                        attent:""},{data: 18,
                                          attent:""},{data: 19,
                                            attent:""},{data: 20,
                                              attent:""},{data: 21,
                                                attent:""},{data:22,
                                                  attent:""},{data:23,
                                                    attent:""},{data: 24,
                                                      attent:""},{data: 25,
                                                        attent:""},{data: 26,
                                                          attent:""},{data: 27,
                                                            attent:""},{data: 28,
                                                            attent:""},{data: 29,
                                                              attent:""},{data: 30,
                                                                attent:""},{data: 31,
                                                                  attent:""}]
    },
    October:{
      type:[Object],
      default:[{data: 1,
        attent:""},{data: 2,
          attent:""},{data: 3,
            attent:""},{data:4,
              attent:""},{data: 5,
                attent:""},{data: 6,
                  attent:""},{data: 7,
                    attent:""},{data: 8,
                      attent:""},{data: 9,
                        attent:""},{data: 10,
                          attent:""},{data: 11,
                            attent:""},{data: 12,
                              attent:""},{data: 13,
                                attent:""},{data: 14,
                                  attent:""},{data: 15,
                                    attent:""},{data: 16,
                                      attent:""},{data: 17,
                                        attent:""},{data: 18,
                                          attent:""},{data: 19,
                                            attent:""},{data: 20,
                                              attent:""},{data: 21,
                                                attent:""},{data:22,
                                                  attent:""},{data:23,
                                                    attent:""},{data: 24,
                                                      attent:""},{data: 25,
                                                        attent:""},{data: 26,
                                                          attent:""},{data: 27,
                                                            attent:""},{data: 28,
                                                            attent:""},{data: 29,
                                                              attent:""},{data: 30,
                                                                attent:""},{data: 31,
                                                                  attent:""}]
    },
    November:{
      type:[Object],
      default:[{data: 1,
        attent:""},{data: 2,
          attent:""},{data: 3,
            attent:""},{data:4,
              attent:""},{data: 5,
                attent:""},{data: 6,
                  attent:""},{data: 7,
                    attent:""},{data: 8,
                      attent:""},{data: 9,
                        attent:""},{data: 10,
                          attent:""},{data: 11,
                            attent:""},{data: 12,
                              attent:""},{data: 13,
                                attent:""},{data: 14,
                                  attent:""},{data: 15,
                                    attent:""},{data: 16,
                                      attent:""},{data: 17,
                                        attent:""},{data: 18,
                                          attent:""},{data: 19,
                                            attent:""},{data: 20,
                                              attent:""},{data: 21,
                                                attent:""},{data:22,
                                                  attent:""},{data:23,
                                                    attent:""},{data: 24,
                                                      attent:""},{data: 25,
                                                        attent:""},{data: 26,
                                                          attent:""},{data: 27,
                                                            attent:""},{data: 28,
                                                            attent:""},{data: 29,
                                                              attent:""},{data: 30,
                                                                attent:""},{data: 31,
                                                                  attent:""}]
    },
    December:{
      type:[Object],
      default:[{data: 1,
        attent:""},{data: 2,
          attent:""},{data: 3,
            attent:""},{data:4,
              attent:""},{data: 5,
                attent:""},{data: 6,
                  attent:""},{data: 7,
                    attent:""},{data: 8,
                      attent:""},{data: 9,
                        attent:""},{data: 10,
                          attent:""},{data: 11,
                            attent:""},{data: 12,
                              attent:""},{data: 13,
                                attent:""},{data: 14,
                                  attent:""},{data: 15,
                                    attent:""},{data: 16,
                                      attent:""},{data: 17,
                                        attent:""},{data: 18,
                                          attent:""},{data: 19,
                                            attent:""},{data: 20,
                                              attent:""},{data: 21,
                                                attent:""},{data:22,
                                                  attent:""},{data:23,
                                                    attent:""},{data: 24,
                                                      attent:""},{data: 25,
                                                        attent:""},{data: 26,
                                                          attent:""},{data:27,
                                                            attent:""},{data: 28,
                                                            attent:""},{data: 29,
                                                              attent:""},{data: 30,
                                                                attent:""},{data: 31,
                                                                  attent:""}]
    },
  },
  { timestamps: true }
);




module.exports = mongoose.model("attendance", attendanceSchema);
